### ISSUE TITLE
Migrate Onboarding tickets 

### ISSUE THREAD

**Issue by sarina** [openedx/training-courses#1]
Migrate tickets from https://github.com/orgs/edx/projects/2 into this project.

**Comment by sarina** [comment]
@mphilbrick211 👋🏻 

Could you let me know the purpose of this board: https://github.com/orgs/edx/projects/2 and what the status of any projects on this board are? It feels abandoned. (no worries if it is!)

**Comment by mphilbrick211** [comment]
@sarina yes, abandoned. This was an edX project that Nimisha helped start that was going to be an onboarding course developed with Omar as lead, along OpenCraft and a few others. I was helping track the project with Omar, but I think capacity became an issue and it ended up not taking flight. I would say it's OK to delete.

**Comment by sarina** [comment]
Great, thanks Michelle 👍🏻
