### ISSUE TITLE
Module 1: Major Community Members unit

### ISSUE THREAD

**Issue by jalondonot** [openedx/training-courses#11]
**Milestone:** Community

**Description**
Creating the content for the "Meet the community" subsection.

**Sub-tasks**
- [x]  "2U/edX " unit
- [x]  "tCRIL" unit
- [x]  "Open edX Providers" unit
- [x] "Contributors" unit

**Definition of Done**
The initial version of the "Meet the community" subsection is published.

**Comment by sarina** [comment]
I put this under one unit, [Module 1 > About the Open edX Project > Major Community Members](https://studio.edunext.co/container/block-v1:tCRIL+OE101+2022+type@vertical+block@eb6f4d95de0d4e07a0225c80130cc569)

It didn't feel right to have big sections for Axim and 2U. Can you review this unit and let me know what you think?

**Comment by mariajgrimaldi** [comment]
We should talk about contributors outside the CC program, like wg members, individual contributors. That could be a line or two here:
![image](https://user-images.githubusercontent.com/64440265/234715990-c7a58661-8205-4734-9ee4-3137b2344526.png)

**Comment by sarina** [comment]
I got an email that @mariajgrimaldi made this comment but I don't see it

We should talk about contributors outside the CC program, like wg members, individual contributors. That could be a line or two here:

![image](https://user-images.githubusercontent.com/1985317/234986633-54d3d24d-16e7-495f-bb13-59480c543c66.png)

**Comment by sarina** [comment]
@mariajgrimaldi I added this, what do you think?

<img width="1401" alt="image" src="https://user-images.githubusercontent.com/1985317/234992900-98ded6cc-eddf-43cd-b920-fac09e1640d1.png">

**Comment by jalondonot** [comment]
I was checking the [Bitergia board](https://openedx.biterg.io/app/kibana#/dashboard/Overview?_g=(refreshInterval:(pause:!t,value:0),time:(from:'2022-01-01T05:00:00.000Z',mode:absolute,to:'2023-01-01T04:59:59.999Z'))&_a=(description:'Overview%20Panel%20by%20Bitergia',filters:!(('$state':(store:appState),meta:(alias:'Empty%20Commits',disabled:!f,index:git,key:files,negate:!t,params:(query:'0',type:phrase),type:phrase,value:'0'),query:(match:(files:(query:'0',type:phrase)))),('$state':(store:appState),meta:(alias:Bots,disabled:!f,index:git,key:author_bot,negate:!t,params:(query:!t,type:phrase),type:phrase,value:true),query:(match:(author_bot:(query:!t,type:phrase))))),fullScreenMode:!f,options:(darkTheme:!f,useMargins:!t),panels:!((embeddableConfig:(title:Git),gridData:(h:8,i:'1',w:16,x:0,y:20),id:git_main_numbers,panelIndex:'1',title:Git,type:visualization,version:'6.8.6'),(embeddableConfig:(title:Commits,vis:(legendOpen:!f)),gridData:(h:8,i:'2',w:16,x:0,y:28),id:git_evolution_commits,panelIndex:'2',title:'Git%20Commits',type:visualization,version:'6.8.6'),(embeddableConfig:(title:Authors,vis:(legendOpen:!f)),gridData:(h:8,i:'3',w:16,x:0,y:36),id:git_evolution_authors,panelIndex:'3',title:'Git%20Authors',type:visualization,version:'6.8.6'),(embeddableConfig:(title:Organizations),gridData:(h:20,i:'5',w:16,x:16,y:0),id:git_commits_organizations,panelIndex:'5',title:Organizations,type:visualization,version:'6.8.6'),(embeddableConfig:(title:'Github%20Issues'),gridData:(h:8,i:'31',w:16,x:32,y:20),id:github_issues_main_metrics,panelIndex:'31',title:'Github%20Issues',type:visualization,version:'6.8.6'),(embeddableConfig:(title:'GitHub%20Issues'),gridData:(h:8,i:'32',w:16,x:32,y:28),id:github_issues_evolutionary,panelIndex:'32',title:'GitHub%20Issues',type:visualization,version:'6.8.6'),(embeddableConfig:(title:'GitHub%20Issues%20Submitters'),gridData:(h:8,i:'33',w:16,x:32,y:36),id:github_issues_evolutionary_submitters,panelIndex:'33',title:'GitHub%20Issues%20Submitters',type:visualization,version:'6.8.6'),(embeddableConfig:(title:'GitHub%20Pull%20Requests'),gridData:(h:8,i:'34',w:16,x:16,y:20),id:github_pullrequests_main_metrics,panelIndex:'34',title:'GitHub%20Pull%20Requests',type:visualization,version:'6.8.6'),(embeddableConfig:(title:'Pull%20Requests'),gridData:(h:8,i:'35',w:16,x:16,y:28),id:github_pullrequests_pullrequests,panelIndex:'35',title:'GitHub%20Pull%20Requests',type:visualization,version:'6.8.6'),(embeddableConfig:(title:'Pull%20Request%20Submitters',vis:(legendOpen:!f)),gridData:(h:8,i:'36',w:16,x:16,y:36),id:github_pullrequests_submitters_evolutionary,panelIndex:'36',title:'GitHub%20Pull%20Request%20Submitters',type:visualization,version:'6.8.6'),(embeddableConfig:(title:Discourse),gridData:(h:8,i:'55',w:16,x:0,y:44),id:discourse_main_metrics,panelIndex:'55',title:Discourse,type:visualization,version:'6.8.6'),(embeddableConfig:(title:'Questions%20and%20Answers'),gridData:(h:8,i:'56',w:16,x:0,y:52),id:discourse_qa_evolutionary,panelIndex:'56',title:'Discourse%20Questions%20and%20Answers',type:visualization,version:'6.8.6'),(embeddableConfig:(title:Participants),gridData:(h:8,i:'57',w:16,x:0,y:60),id:discourse_qa_evolutionary_submitters,panelIndex:'57',title:'Discourse%20Participants',type:visualization,version:'6.8.6'),(embeddableConfig:(title:Slack),gridData:(h:8,i:'65',w:16,x:16,y:44),id:slack_main_numbers,panelIndex:'65',title:Slack,type:visualization,version:'6.8.6'),(embeddableConfig:(title:'Slack%20Messages'),gridData:(h:8,i:'66',w:16,x:16,y:52),id:slack_messages_evolutionary,panelIndex:'66',title:'Slack%20Messages',type:visualization,version:'6.8.6'),(embeddableConfig:(title:'Slack%20Participants'),gridData:(h:8,i:'67',w:16,x:16,y:60),id:slack_participants_evolutionary,panelIndex:'67',title:'Slack%20Participants',type:visualization,version:'6.8.6'),(embeddableConfig:(title:'Git%20Top%20Authors',vis:(params:(config:(searchKeyword:''),sort:(columnIndex:!n,direction:!n)))),gridData:(h:20,i:'111',w:16,x:0,y:0),id:git_overview_top_authors,panelIndex:'111',title:'Git%20Top%20Authors',type:visualization,version:'6.8.6'),(embeddableConfig:(title:'Git%20Top%20Projects',vis:(params:(config:(searchKeyword:''),sort:(columnIndex:!n,direction:!n)))),gridData:(h:20,i:'112',w:16,x:32,y:0),id:git_overview_top_projects,panelIndex:'112',title:'Git%20Top%20Projects',type:visualization,version:'6.8.6')),query:(language:lucene,query:(query_string:(analyze_wildcard:!t,default_field:'*',query:'*'))),timeRestore:!f,title:Overview,viewMode:view)) to make sure we're not missing anyone here, and I noticed the MIT is the 3° contributor on this list. I know we're already mentioning them in "edX, a 2U Company". Is this enough or should we be more explicit about Harvard and MIT's current contribution to the project? these are big names that could attract a lot of potential new contributors :)

What do you think, @sarina @mariajgrimaldi?

**Comment by sarina** [comment]
I think that's a good idea. I added this sentence:

> Harvard and MIT founded edX back in 2012. Today, they are both major contributors to the Open edX project.

I'm not sure what else to say, though.

**Comment by mariajgrimaldi** [comment]
Thanks for the changes @sarina! It looks really good! I deleted the comment by mistake (?), or something else was going through my mind, I can't remember what.

**Comment by mariajgrimaldi** [comment]
Should we close this?
