### ISSUE TITLE
Module 2: Join us Subsection

### ISSUE THREAD

**Issue by jalondonot** [openedx/training-courses#14]
**Milestone:** Contrubutions

**Description**
Creating the content for the "Join us" subsection.

**Sub-tasks**
- [ ]  "Next steps" unit
- [ ]  "Where to contribute" unit

**Definition of Done**
The initial version of the "Join us" subsection is published.

**Comment by sarina** [comment]
This is ready for review

**Comment by mariajgrimaldi** [comment]
A few comments:
**Communication tooks**
- We usually refer to discourse as _discuss_. For example: I read your post on discuss... I know it's a bit silly, but should we add that reference when talking about it?
- I like what you did with the titles and the tools' names! Can we use png images for slack and confluence?

**Maintainership Program**

> Need information on how you find the maintainer of a repo, how you reach out to them, when you should reach out to them
How to find a maintainer -> we could use backstage for this
How to reach out -> GH issues, discuss, slack maybe
When -> a few examples: I found a bug! I want a new feature for this library, how can I implement X using this library? and so on 

what do you think?

**Comment by sarina** [comment]
> We usually refer to discourse as discuss. For example: I read your post on discuss... I know it's a bit silly, but should we add that reference when talking about it?

Funny, we always call it Discourse. I added this line at the beginning: `[Discourse](https://discuss.openedx.org/) (also called "Discuss")`

> I like what you did with the titles and the tools' names! Can we use png images for slack and confluence?

How can you tell the difference? The image for Confluence was a screenshot of the wiki, so I'm pretty dang sure it's a PNG. What is the advantage of using only PNGs?

> Maintainer ship

How does this look?
<img width="941" alt="image" src="https://user-images.githubusercontent.com/1985317/234998320-db388215-025b-4503-ae7b-dbf954674604.png">

Honestly, I worry this concept - especially at this detail - is too technical for the audience we're aiming at overall. I certainly wouldn't want this to be any _more_ technical.

**Comment by jalondonot** [comment]
I agree with @sarina . Wouldn't be better to just redirect them to this [article](https://openedx.org/blog/open-edx-maintainers-program/#:~:text=The%20term%20%E2%80%9Cmaintainer%E2%80%9D%20refers%20to,both%20technical%20and%20community%20management.) and the [slack channel](https://openedx.slack.com/archives/C03R320AFJP) as a first point of contact, @mariajgrimaldi ?

**Comment by mariajgrimaldi** [comment]
No for now! Thank you. LGTM
