### ISSUE TITLE
Module 3: Introduction to Contributing

### ISSUE THREAD

**Issue by jalondonot** [openedx/training-courses#16]
**Milestone:** Contributions

**Description**
Creating the content for the "Non-code contributions" subsection.

**Sub-tasks**
- [x]  "Contributing" unit
- [x] Join the community unit
- [x] Finding Contributions unit
- [ ] Resources directory

**Definition of Done**
The initial version of the "Non-code contributions" subsection is published.

**Comment by sarina** [comment]
[Section is live here](https://training.openedx.org/courses/course-v1:Axim+Open-edX-Intro+2023/courseware/593f0b01bbc84e3ebc1871d0c0157b48/04abda9229384c77ac891fcebe708031/3?activate_block_id=block-v1%3AAxim%2BOpen-edX-Intro%2B2023%2Btype%40vertical%2Bblock%40202eaa7fd5944cef941c17ed1d67f81c)

I admit I don't know what to put in the "Resources Reference" unit. Any thoughts @mariajgrimaldi @jalondonot ?

**Comment by sarina** [comment]
Thanks Maria!

**Comment by mariajgrimaldi** [comment]
About the references, we could add:

- Our official documentation: https://docs.openedx.org/en/latest/
- Tutor documentation: https://docs.tutor.overhang.io/
- Arch and engineering space: https://openedx.atlassian.net/wiki/spaces/AC/overview?homepageId=7766132

**Comment by sarina** [comment]
Added! (Actually I added a "Coding Resources" page to the Code Contributions subsection, and added the more technical resources - like Tutor - there)
