### ISSUE TITLE
2022-10-21 Meeting Notes & To-Dos

### ISSUE THREAD

**Issue by sarina** [openedx/training-courses#17]
Putting our meeting notes here so we remember outcomes; the aim is to have this todo list finished by next meeting. (Nov 4). Note I will be away Nov 4th. I can either give an update in advance or we could move the checkin to Nov 7th.

@sarina  Finish CC onboarding text & identify people to record videos

@mariajgrimaldi Focus on authoring Open edX project section, survey to people like Sarina & Dave

@jalondonot  Start organizing modules & make forums discuss post

All: Get all issues on the board https://github.com/orgs/openedx/projects/15 in the right status, with the correct metadata set

**Comment by sarina** [comment]
My to-do items for next sprint:

- [ ] https://github.com/openedx/training-courses/issues/18
- [ ] https://github.com/openedx/training-courses/issues/20

**Comment by sarina** [comment]
label: project notes 📝

**Comment by mariajgrimaldi** [comment]
@jlondonot we also agreed on using extra fields / labels for categorizing the issues on the kanban board instead of milestones. Those are easier to use and understand than milestones

**Comment by sarina** [comment]
I think we're done with this issue! Good job everyone.
