### ISSUE TITLE
Exclusive CC videos prep

### ISSUE THREAD

**Issue by sarina** [openedx/training-courses#20]
- [x] Identify which videos need to get made
- [x] Write script bullets
- [x] Identify people to record each video

Note this does not include WG intro videos - we'll share those with the community onboarding course

**Comment by sarina** [comment]
Videos needed:

* Welcome to CC program! (short - 2 min? - like good job you're awesome and thank you!) - Sarina
* CC program overview (2-4 min - basically hit on the main points of each section in the unit) - can I get Dean to do this? I have a script
* Rights/Responsibilities video (short - could be me and Xavier doing a reprise of our conference talk. Could be one or two videos) - Sarina/Xavier
* a short video introducing the "Diving In" unit (would help an otherwise all-text section) - Sarina

There's no video slated for the "Coders" section. I'm not sure there needs to be one though

**Comment by DeanJayMathew** [comment]
Hey Sarina! I would love to give this a try. Feel free to send me the
script and any other directions if applicable.

**Comment by sarina** [comment]
@DeanJayMathew can't believe you're watching this!! :) 

You can find a draft script here: https://docs.google.com/document/d/1QOSwnr3KdqYF9fK4wC00KGtfoT3J__FhWGI6q5vJWAk/edit# - please edit/comment. I would really appreciate your help - thank you.
