### ISSUE TITLE
"What's next?" Subsection (Module 2)

### ISSUE THREAD

**Issue by sarina** [openedx/training-courses#28]
**Milestone:** The Open edX Project

**Description**
Creating the content for the "What's next?" subsection.

**Sub-tasks**
- [x]  Recap of the section
- [ ] Feedback unit
- [ ] ????

**Definition of Done**
The initial version of the "What's next?" subsection is published.

**Comment by sarina** [comment]
Relates to #9 - whatever we decide to do there should reflect on this ticket

**Comment by mariajgrimaldi** [comment]
Can we do takeaways for this module as we did for module 1? As a tiny summary

**Comment by sarina** [comment]
This kinda is a tiny summary. How would you rewrite / what detail is missing?




This unit covered:

* All the communications mediums of the Open edX project (Discourse, Confluence wiki, GitHub, Slack, docs.openedx.org documentation site) and gave some tips on when to use what type of site
* The [Open edX working groups](https://openedx.org/wgs) - what they are and how to participate in them
* The monthly Open edX meetups, and the yearly conference
* How to participate in the creation and testing of Named Releases
* How to become a Core Contributor and a Maintainer

**Comment by mariajgrimaldi** [comment]
About the Who, _Why and Waht: Community_ subsection:
According to Pierre's feedback, should we change:

> Many of the features included in the Open edX platform are collaboratively developed [[1]](https://openedx.org/community/).

To:

Many of the features included in the Open edX platform are collaboratively developed by the [Open edX community](https://openedx.org/community/).

About the takeaways: 

- The Open edX Community is a global group of diverse individuals working together to improve the Open edX platform, believing in accessible education for all. 
- As a community, we use different communications mediums: Discourse, Confluence wiki, GitHub, Slack or the docs.openedx.org documentation site. Each site is helpful for different situations.
- There are several ways of contributing to the project, like being part of one of the [Open edX working groups](https://openedx.org/wgs) 
- There is a monthly Open edX meetup, and a yearly conference
- Another way of contributing is participating in the creation and testing of Named Releases
- You can also become a Core Contributor or be part of the Maintainer program

The other takeaways also follow this structure, so we're good I think!

**Comment by sarina** [comment]
Addressed, thank you!
