### ISSUE TITLE
Module 3: What's Next

### ISSUE THREAD

**Issue by sarina** [openedx/training-courses#30]
**Milestone:** The Open edX Project

**Description**
Creating the content for the "What's next?" subsection.

**Sub-tasks**
- [x]  Recap of the section
- [x] Feedback unit
- [x] ????

**Definition of Done**
The initial version of the "What's next?" subsection is published.

**Comment by sarina** [comment]
This is ready for review @jalondonot @mariajgrimaldi

**Comment by mariajgrimaldi** [comment]
@sarina @jalondonot: there was a what's next had __This unit covered:__ before the takeaways while the others didn't. So I removed it! Do you folks like it like that or with the subtitle?

**Comment by sarina** [comment]
I think either "Takeaways" or "This unit covered" is fine. I wonder if "This unit covered" would be easier for people who don't speak English well?

**Comment by mariajgrimaldi** [comment]
Mmm, I didn't think about that. Maybe you're right

**Comment by sarina** [comment]
Made it all consistent in all 3 units
