### ISSUE TITLE
Conclusion / Wrapping Up

### ISSUE THREAD

**Issue by sarina** [openedx/training-courses#31]
**Milestone:** The Open edX Project

**Description**
Creating the content for the Conclusion section.

**Sub-tasks**
- [ ]  Wrapping Up subsection
- [ ] Congrats! subsection

**Definition of Done**
The initial version of the "Conclusion" section is published.

**Comment by sarina** [comment]
@jalondonot @mariajgrimaldi I'm not sure what to put for a conclusion. I made a cute graphic but should there be anything else? We already did summaries of each module so repeating that felt, well, repetitive.

You can see the congrats graphic [here](https://training.openedx.org/courses/course-v1:Axim+Open-edX-Intro+2023/courseware/84cf0496b029497e9c153e03277a25c6/2989635f3d534fdaa25ad8c4511e965d/1?activate_block_id=block-v1%3AAxim%2BOpen-edX-Intro%2B2023%2Btype%40vertical%2Bblock%404a1e8ed7443f45ca8b7b168c122f5f0a)

**Comment by sarina** [comment]
or here!

![Congrats - Open edX intro (1080 × 608 px)](https://user-images.githubusercontent.com/1985317/235066481-392798e0-0590-4a5f-af41-00260136b610.png)

**Comment by sarina** [comment]
We already have the takeaways at the end of each section. Are you suggesting we should also do a takeaway for the whole course at the end here?

**Comment by sarina** [comment]
What about a checklist for jumping into the community? Like,

- Check out the Demo Course
- Read through the list of active working groups
- Be a guest at a working group meeting
- Introduce yourself on the forums (maybe we start an Intro thread we link to?)

Not sure what else

**Comment by mariajgrimaldi** [comment]
> We already have the takeaways at the end of each section. Are you suggesting we should also do a takeaway for the whole course at the end here?

I meant to ask which of those possibilities is better, at the end of the sections or the end of the course 🤔. We could review that for a V2 after we get some feedback!

**Comment by mariajgrimaldi** [comment]
I like that idea! We could add at the end:
- Pick up some work from the working group of your liking and start interacting with other contributors
- Or try solving bugs reported on our community channels! 
If you still don't know where to start, contact the community members on the channels available!

**Comment by sarina** [comment]
Good additions, thanks!

I like the summary per-unit, it's easier to summarize a small bit. I'm open to doing a course-wide summary as well, but I think the course is short enough that it's not necessary.
