### ISSUE TITLE
Outline Open edX Onboarding course

### ISSUE THREAD

**Issue by mariajgrimaldi** [openedx/training-courses#6]
### Description
Create outline (sections/subsections/units) with descriptions for the [Open edX Onboarding](https://studio.edunext.co/course/course-v1:tCRIL+OE101+2022) course in the training instance.

### Sub-tasks
- [x] Each section has an `about this section`.
- [x] Each unit has components with information about what to add.

### Definition of Done
The Open edX Onboarding course has a 1st version outline published.

### More resources
- Find the proposed outline [here](https://docs.google.com/document/d/1PV7oLODJdR9NDTQ7TKYEKX4KXX2TkRQaBuo_4BS5vTY/edit?usp=sharing), this outline may vary during the course development, this is just 1st version.

**Comment by mariajgrimaldi** [comment]
@sarina: hello! :dancers: 
can you give us permissions to create labels? should we group together the issues per course with milestones? :thinking: 
cc @jalondonot

**Comment by sarina** [comment]
You should now be able to start a comment with `label: <label-name>` and it'll apply the label!
